/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ControlDescription {
        "code": string;
    }
    interface ControlDescriptionSheet {
    }
    interface CourseHeading {
        "climb"?: string;
        "length"?: string;
        "number"?: string;
    }
    interface SpecialInstruction {
    }
}
declare global {
    interface HTMLControlDescriptionElement extends Components.ControlDescription, HTMLStencilElement {
    }
    var HTMLControlDescriptionElement: {
        prototype: HTMLControlDescriptionElement;
        new (): HTMLControlDescriptionElement;
    };
    interface HTMLControlDescriptionSheetElement extends Components.ControlDescriptionSheet, HTMLStencilElement {
    }
    var HTMLControlDescriptionSheetElement: {
        prototype: HTMLControlDescriptionSheetElement;
        new (): HTMLControlDescriptionSheetElement;
    };
    interface HTMLCourseHeadingElement extends Components.CourseHeading, HTMLStencilElement {
    }
    var HTMLCourseHeadingElement: {
        prototype: HTMLCourseHeadingElement;
        new (): HTMLCourseHeadingElement;
    };
    interface HTMLSpecialInstructionElement extends Components.SpecialInstruction, HTMLStencilElement {
    }
    var HTMLSpecialInstructionElement: {
        prototype: HTMLSpecialInstructionElement;
        new (): HTMLSpecialInstructionElement;
    };
    interface HTMLElementTagNameMap {
        "control-description": HTMLControlDescriptionElement;
        "control-description-sheet": HTMLControlDescriptionSheetElement;
        "course-heading": HTMLCourseHeadingElement;
        "special-instruction": HTMLSpecialInstructionElement;
    }
}
declare namespace LocalJSX {
    interface ControlDescription {
        "code"?: string;
    }
    interface ControlDescriptionSheet {
    }
    interface CourseHeading {
        "climb"?: string;
        "length"?: string;
        "number"?: string;
    }
    interface SpecialInstruction {
    }
    interface IntrinsicElements {
        "control-description": ControlDescription;
        "control-description-sheet": ControlDescriptionSheet;
        "course-heading": CourseHeading;
        "special-instruction": SpecialInstruction;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "control-description": LocalJSX.ControlDescription & JSXBase.HTMLAttributes<HTMLControlDescriptionElement>;
            "control-description-sheet": LocalJSX.ControlDescriptionSheet & JSXBase.HTMLAttributes<HTMLControlDescriptionSheetElement>;
            "course-heading": LocalJSX.CourseHeading & JSXBase.HTMLAttributes<HTMLCourseHeadingElement>;
            "special-instruction": LocalJSX.SpecialInstruction & JSXBase.HTMLAttributes<HTMLSpecialInstructionElement>;
        }
    }
}
